import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import jwt from 'jsonwebtoken'
import { NextResponse } from 'next/server'
import { NextRequest } from 'next/server'
import { middleware } from './middleware.js'



// const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  // middleware()
  
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [message, setMessage] = useState('You are not logged in')
  const [secret, setSecret] = useState('')


  return (
    <>
      <h1>{message}</h1>
      <h1>{secret}</h1>
      <Head>
        <title>Wow hello hi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div>
        <form method="POST" action="/api/login">
          <input
            type="text"
            name="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
          <br />
          <input
            type="password"
            name="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <br />
          <input type="button" value="Login" onClick={submitForm}/>
        </form>
      </div>
    </main>
    </>
  );

  async function submitForm() {

    // const { globalState, setGlobalState} = React.useContext(GlobalContext);
    // const { url } = globalState;
  

    const res = await fetch('/api/login', {
      method: "POST",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ username, password })
    }).then((t) => t.json())

    const token = res.token
    // console.log(token)
    const json = jwt.decode(token)
    console.log(token)
    console.log(json)
  
    if(json.username) {

      console.log('here now')
      const string_token = JSON.stringify({ token })
      const json_token = JSON.stringify({ token })
      
      console.log(json)
      console.log(token)
      console.log(string_token)
      console.log(json_token)

      setMessage(`Welcome ${json.username}`)

      const res = await fetch('/api/secret', {
        method: "POST",
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ token })
      }).then((t) => t.json())


      setSecret(res.secretAdminCode)

      await window.localStorage.setItem("token", token);
      // await localStorage.setItem("token", JSON.stringify(state));
      // setGlobalState({
      //   ...globalState,
      //   token: token,
      // })
      // NextResponse.redirect(new URL('api/hello', request.url))
    } else {
      setSecret('Nothing Avaliable')
    }
  }
  

}
